CREATE TABLE IF NOT EXISTS roadmaps (
  id CHAR(36) NOT NULL,
  title VARCHAR(140) NOT NULL,
  author VARCHAR(60) NOT NULL,
  description VARCHAR(2000) NOT NULL,
  stops VARCHAR(1200) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_roadmaps_updated (updated_at)
) ENGINE = InnoDB;
